name: CI-CD Backend

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region us-east-1 \
        | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

    - name: Build Docker image
      run: |
        docker build -t backend ./backend
        docker tag backend:latest ${{ secrets.ECR_REPO_URL_BACKEND }}:latest

    - name: Push to ECR
      run: |
        docker push ${{ secrets.ECR_REPO_URL_BACKEND }}:latest

    - name: Deploy to EC2 via SSM
      run: |
        aws ssm send-command \
        --instance-ids "${{ secrets.EC2_BACKEND_INSTANCE_ID }}" \
        --document-name "AWS-RunShellScript" \
        --parameters commands="docker pull ${{ secrets.ECR_REPO_URL_BACKEND }}:latest && docker stop backend || true && docker rm backend || true && docker run -d --name backend -p 8080:8080 ${{ secrets.ECR_REPO_URL_BACKEND }}:latest"
